### ISSUE TITLE
Breaks, if batch contains less processes than maximum allowed

### ISSUE THREAD

**Issue by tautrimas** [jagandecapri/symfony-parallel-process#3]
https://github.com/jagandecapri/symfony-parallel-process/blob/8d0b7ea688aece924fc01d6ee79a9e2f0fd2ebd5/src/ProcessManager.php#L53 breaks, if batch contains less processes than maximum allowed

**Comment by jagandecapri** [comment]
@tautrimas Nice catch. Yeah, looks like the for loop checking of `$i < $max_parallel` is redundant as there is already an `array_chunk` before that.

**Comment by tautrimas** [comment]
I almost totally rewrote your class to allow process slots to be fully occupied instead of batch running and waiting for the last batch element to finish. I hope I can contribute a PR soon.

**Comment by jagandecapri** [comment]
That's great. Please send in a PR. :)

**Comment by vertexvaar** [comment]
I think this bug report is obsolete, since the code has undergone a huge change ;)

**Comment by jagandecapri** [comment]
@vertexvaar Yeap, you are right. Closing it.
